Style entities decoder
unreal4u/telegram-api pull request #141
Opened 2022-01-20 22:14 UTC by LucaDevelop

Hi there,
I've created this class to read the text (or the caption) and the entities from message object and return the text with inline entities (HTML, MarkdownV2 or Markdown) that replicate the original styles but with the possibility to manipulate it afterwards.
I've used it in several bots of mine alongside your library and I've decide to add it directly in the Message class.

This is the repo of my class: https://github.com/LucaDevelop/telegram-entities-decoder

I hope it can be useful.

2022-01-21 11:41 UTC, unreal4u requested changes
hi!

Thanks for submitting this PR! 

While I am a bit reticent to add methods to a `Type` (which comes from Telegram themselves) I understand there is no other place where we could do this type of stuff and there would need to be some major refactoring in order for us to be able to do this in any other way. 

Can you pick up the comments I left so that I can approve it? Thanks!

2022-01-21 11:41 UTC, unreal4u commented on src/Telegram/Types/Message.php
> +     * Decode style entities from Telegram bot messages (bold, italic, etc.) in text with inline entities that duplicate (when possible) the exact style the message had originally when was sended to
PHPDocumentor require us to come up with a title that explains in less than 80 chars what a method will do.

In the long description (with 2 enters after the title) you can go as long as you want, while always adhering to the 120 chars line length :)

2022-01-21 11:41 UTC, unreal4u commented on src/Telegram/Types/Message.php
> +     * @param string $style
As for comments, this is the place to talk about accepted values. 

You can do something like `@param string $style Use 'HTML', 'MarkdownV2' or 'Markdown'`

2022-01-21 11:41 UTC, unreal4u commented on src/Telegram/Types/Message.php
> +        $entitiesDecoder = new EntityDecoder($style);
What happens if the passed style is invalid? Does it throw an exception? If so, add a `@throws` comment above or perform some kind of validation here. 

Ideally, you library should handle this but I saw you don't throw anything on the constructor here: https://github.com/LucaDevelop/telegram-entities-decoder/blob/master/src/EntityDecoder.php#L30

2022-01-21 11:41 UTC, unreal4u commented on src/Telegram/Types/Message.php
> +    public function decodeEntities($style = 'HTML')
Don't forget to add the return type `: string` to this method :)

2022-01-22 07:57 UTC, LucaDevelop commented
Hi,
thanks for considering my PR. I'm on it with the changes you've requested.

2022-04-04 07:35 UTC, unreal4u commented
Sorry it took so long @LucaDevelop but I didn't receive ANY notification of your changes! Just happened to stumble across it now and saw that you submitted all changes, I'll review my notification settings so it doesn't happen again!

2022-04-04 07:35 UTC, merged